openapi: 3.0.0
info:
  title: Petimus
  version: '1.0'
  description: Petimus API for create and manage test.
servers:
  - url: 'http://localhost:3000'
paths:
  /theme:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Theme'
      operationId: get-theme
      description: Get the list of theme from a domain.
  '/theme/{theme_id}':
    parameters:
      - schema:
          type: string
        name: theme_id
        in: path
        required: true
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Theme'
      operationId: get-theme-theme_id
      description: Information from a specific theme
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties: {}
          application/xml:
            schema:
              type: object
              properties: {}
components:
  schemas:
    Theme:
      title: Theme
      type: object
      properties:
        theme_id:
          type: string
        theme_name:
          type: string
      x-examples:
        example-theme:
          theme_id: '001'
          theme_name: Javascript
      description: Definition of a theme.
    Category:
      title: Category
      type: object
      description: Every Theme has a list of categories.
      properties:
        category_id:
          type: string
        category_name:
          type: string
      x-examples:
        example-category:
          category_id: '001'
          category_name: Arrays
    Test:
      title: Test
      type: object
      properties:
        id:
          type: string
      description: A Test
    Question:
      title: Question
      type: object
      properties:
        id:
          type: string
      description: A question of the test.
